# print('Olá bem vindo!')
# print("Vamos para o nosso 3º projeto!")
# n1 = int(input('Digite o Primeiro Número:'))
# n2 = int(input('Digite o Segundo Número:'))
# s = (n1 + n2)
# print('A Soma de {} e {} gera esse valor {}'.format(n1, n2, s)) >> o .format foi atualizado para o exemplo a baixo.
# print('===== DESAFIO 3 =====')
# n1=int(input('Digite o 1º Numero: '))
# n2=int(input('Digite o 2º numero: '))
# print(f'A soma entre {n1} e {n2} é igual a ',n1+n2)
print(' .: Desafio 003 :.')
n1 = int(input('Digite o 1º número: '))
n2 = int(input('Digite o 2º número: '))
print(f'A soma entre {n1} e {n2} é igual a ', n1 + n2)
