print('.: Desafio 004 :.')
#print(' Vamos descobrir o type de cada exemplo.')
#n1 = input('Digite algo: ')
#print(n1.isalnum())
#n2 = input('Digite um algo: ')
#print(n2.isalpha())
#n3 = input('Diite um algo: ')
#print(n3.isdigit())
#n4 = input('Digite um algo: ')
#print(n4.islower())
a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaço? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabética:', a.isalpha())
print('É alphanumérico?', a.isalnum())
print('Esta em maiúscula?', a.isupper())
print('Esta em minúscula?', a.islower())
print('Está captalizado?', a.istitle())


