print('.' * 100)
print('.: Cálculo de Custo por Km :.')
print('-' * 100)
kmdia = float(input('Digite Km/dia Rodado: '))
semana = int(input('Digite Semanas do Mês: '))
dias = int(input('Quantidade de Dias Rodados: '))
tanque = int(input('Quantidade Litros por Tanque: '))
litro = float(input('Valor do Litro Pago: '))
média = float(input('Média do Veículo: '))
print(f'Distância: {kmdia:.2f} km \nDias: {dias}')
print('.' * 100)
print(f'Kilometragem Mensal é de {kmdia * dias:.2f} km/mês')
print(f'Quantidade de tanques por mês {((tanque * média) *  ((kmdia * média) / (tanque * média)) / (tanque * litro)):.0f} tanques')
print(f'Distância Percorrida com um Tanque: {tanque * média:.0f} km')
print(f'Valor à pagar Mensal: R$ {(tanque * média) *  ((kmdia * média) / (tanque * média)):.2f}')
print(f'Custo por Semana: R$ {((tanque * média) *  ((kmdia * média) / (tanque * média))) / semana:.2f}')
print(f'Custo por Tanque: R$ {tanque * litro:.2f}')
print(f'Custo por Dia: R$ {(tanque * média) *  ((kmdia * média) / (tanque * média)) / dias:.2f}')
print('-' * 100)
print(' Up Hill -' * 10)
#print('.: DESAFIO 15 :.')
#print(f'Escreva um programa que pergunte a quantidade de Km percorridos por um carro alugado \ne a quantidade de dias pelos quais ele foi alugado.')
#print('Calcule o preço a pagar, sabendo que o carro custa R$ 60 e R$ 0,15 Km rodado.')
#km = float(input('Digite KM rodado: '))
#dias = int(input('Quantidade de dias: '))
#print(f'Distância: {km} km \nDias: {dias} \nValor à pagar: R$ {(dias * 60) + (km * 0.15):.2f}')